@host = https://api-endl.onrender.com

@authToken = {{loginAdmin.response.body.token}}

###

# @name loginAdmin
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "correo": "ana.gomez@example.com",
    "contraseña": "passwordSeguro123"
}

###
GET {{host}}/api/users
Authorization: Bearer "{{authToken}}"

###

POST {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nombre": "Carlos",
  "apellidos": "Rivas",
  "nick": "crivas_admin",
  "correo": "carlos.rivas@example.com",
  "contraseña": "PasswordSuperSegura789",
  "perfil_id": "68f059ef20f76df3e46139a5"
}

###

# @name loginAdmin
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "correo": "carlos@example.com",
    "contraseña": "passwordSeguro123"
}